# Generated by Django 3.1.7 on 2021-04-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.IntegerField(unique=True)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'issues',
                'db_table': 'issue',
                'ordering': ['-issue_num'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('appears_in', models.ManyToManyField(related_name='contributors', to='beholder.Issue')),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pub_date', models.DateField()),
                ('metades', models.CharField(default='magazine page', max_length=300)),
                ('page', models.IntegerField()),
                ('css_class', models.CharField(choices=[('poem', 'poem'), ('long', 'long form'), ('short', 'short form'), ('comic', 'comic'), ('gallery', 'image gallery'), ('soloimg', 'single image'), ('ednote', 'editors note')], default='short', max_length=7)),
                ('body', models.TextField()),
                ('creator', models.ManyToManyField(related_name='contributions', to='beholder.Person')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='beholder.issue')),
            ],
            options={
                'verbose_name_plural': 'contents',
                'db_table': 'content',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('pseudonym', models.CharField(blank=True, max_length=50)),
                ('social_url', models.URLField(null=True)),
                ('person_url', models.URLField(null=True)),
                ('bio_text', models.TextField()),
                ('bio_img_url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beholder.person')),
            ],
            options={
                'verbose_name_plural': 'bios',
                'db_table': 'bio',
            },
        ),
    ]
