# Generated by Django 3.1.7 on 2021-04-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover_img_url',
            field=models.URLField(null=True),
        ),
    ]
