# Generated by Django 3.2.4 on 2021-06-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0003_auto_20210624_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'ordering': ['person'], 'verbose_name_plural': 'bios'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
