# Generated by Django 3.2.4 on 2021-06-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0004_auto_20210625_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='toc_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beholder.person'),
        ),
        migrations.AddField(
            model_name='issue',
            name='toc_img_url',
            field=models.URLField(blank=True),
        ),
    ]
