# Generated by Django 3.2.4 on 2021-06-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0005_auto_20210627_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='toc_artist',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='toc_img_url',
        ),
        migrations.AddField(
            model_name='content',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='toc_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_issue', to='beholder.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
