# Generated by Django 3.2.4 on 2021-07-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0006_auto_20210627_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='slug',
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
