# Generated by Django 3.2.4 on 2021-07-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0007_auto_20210714_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='metades',
        ),
    ]
