# Generated by Django 3.2.4 on 2021-07-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beholder', '0008_remove_content_metades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='content',
            name='css_class',
            field=models.CharField(choices=[('poem', 'poem'), ('long', 'long form'), ('short', 'short form'), ('comic', 'comic'), ('gallery', 'image gallery'), ('soloimg', 'single image'), ('ednote', 'editors note'), ('other', 'other')], default='short', max_length=7),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='untitled', max_length=250),
        ),
        migrations.AlterField(
            model_name='issue',
            name='toc_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_issue', to='beholder.content'),
        ),
    ]
